### ISSUE TITLE
Add 'upgrade' function

### ISSUE THREAD

**Issue by juliancwirko** [ElvenTools/elven-tools-cli#1]
The tools should also have the `upgrade` function for upgrading the smart contract if needed.

**Comment by tannerhallman** [comment]
Would love support for this as the ability to make changes to the contract (especially while in development is key). How can I help?

**Comment by juliancwirko** [comment]
related: https://github.com/juliancwirko/elven-nft-minter-sc/issues/24

**Comment by PABourdais** [comment]
So I guess that for the moment we can't upgrade the SC ?

**Comment by juliancwirko** [comment]
Improvements are tracked on the project's Kanban board now.

https://github.com/orgs/ElvenTools/projects/6/views/1?pane=issue&itemId=47244149
