### ISSUE TITLE
Review and update gas limit calculation where applicable

### ISSUE THREAD

**Issue by juliancwirko** [ElvenTools/elven-tools-cli#25]
There were changes on the smart contract and the devnet/testnet configuration, so the CLI has to be adjusted with new gas limits for a couple of endpoints/commands.

**Comment by tannerhallman** [comment]
I think I am running into this.... randomly the issue token on devnet stopped working.

https://devnet-explorer.elrond.com/transactions/f445fce1c6c9d9a66ae8bacfb7c36d02cb18bb9dcefa5d25616b96c668e280c9


![k8XZLENO](https://user-images.githubusercontent.com/10327491/156087287-b438bbb3-913b-46a4-8f62-f1dd78b80809.jpg)

**Comment by juliancwirko** [comment]
This isn't related to that, probably problems with the smart contract. Here we need to optimize the gas limits set by default because the new setup on chains is more efficient. All operations consume less gas now. Of course, assuming that the smart contract is optimized correctly (elven tools is from version 1.5.0). 

You can always check this by running `erdpy contract report` with the newest version of erdpy and the newest elrond-wasm version. The report should show no `has-allocator`. More about the problem here: https://docs.elrond.com/developers/developer-reference/smart-contract-developer-best-practices/#the-dynamic-allocation-problem

**Comment by tannerhallman** [comment]
I think my issue is that I wasn't using the latest version of your CLI & SC template and you fixed it in a subsequent update. Thanks so much.
