### ISSUE TITLE
Small Typo mistake

### ISSUE THREAD

**Issue by PABourdais** [ElvenTools/elven-tools-cli#27]
https://github.com/juliancwirko/elven-tools-cli/blob/main/src/config.ts

```
export const nftMinterTokenSellingPrice =
  customConfig?.config?.nftMinterSc?.tokenSelingPrice;
```

Typo: tokenSellingPrice

Have a good day

**Comment by juliancwirko** [comment]
Thanks. I'll fix that with the next update, which is planned soon.
