### ISSUE TITLE
Mint gas limit

### ISSUE THREAD

**Issue by Buky33** [ElvenTools/elven-tools-cli#36]
Hey, how are you today?
I am still playing with your suite of tools and i am facing a new problem since yesterday.
I can't mint anymore from the cli tool as I minted several ntfs without any issues last week with the same commands.

Previously to this issue, I checked standard things like the max nft I can mint, the supply, ... everything seems OK, and i still can mint from the dapp. Only the cli fails.
The error is "not enough gas"

Here is the command to reproduce as you could expect:
$> elven-tools nft-minter mint
> 1
> yes
Transaction status: fail
Transaction link: https://devnet-explorer.elrond.com/transactions/f804c4ed1f6d5cc8f7cf2b57f95de6968b341269eb80334e0214bb94f7f02e0b

Here is the transaction ok from the dapp:
https://devnet-explorer.elrond.com/transactions/15db49886482a849735cbb7f559d54cc224712795be6cba6adf7b794d14ebb87#277f01e982fd1b7ad89e48bba189cea5eeada001e249a02e1cdb284a0742e5a6

You can notice that the gas limit is 14,000,000, when its (only) 12,500,000 from the cli command, and the needs is 12,774,693.

Something would have changed on the side of Elrond devote according to you?
Hope you can help ^^

++

**Comment by Buky33** [comment]
Here is the mint that worked fine last week with the cli command:
https://devnet-explorer.elrond.com/transactions/47b8a3aa9bf51e8b809d7454b83e802e930c012cc148e76447b610fa4372b664#6b86653cc897154435cca0343c8ad5f934a7e5624f44bee352014d364c9d8384

The gas limit was already 12,500.... but the gas used was 11,229,015.
It seems that the blockchain needs more gas today ^^

**Comment by juliancwirko** [comment]
Hey, strange, I just minted this using the CLI: https://devnet-explorer.elrond.com/transactions/a2df2cdd73e805f7d075bf88610edde03843ec3f5160a6ff557d72db691795c9.

What version of the CLI and SC? 

Also, have you modified the smart contract?

**Comment by Buky33** [comment]
Yes i changed something, forgot to tell, i created drops

**Comment by Buky33** [comment]
im using elven-tools v 1.9.4

**Comment by juliancwirko** [comment]
Yes, so the gas limits in CLI are adjusted to be optimal for not modified smart contract. If you changed something, then you will need to alter the gas limits using the CLI's configuration file or using a custom and modified CLI for that

**Comment by Buky33** [comment]
Interesting thanks you for the tip.
Do you insinuate that the dapp calculate larger gas limit or maybe it takes in account the drop changes to have a specific gas calc?

I encountered another interesting thing in the dapp with a collection limit test (no more nft in the supply, and still trying to mint from the dapp), the popup told me the transaction was successful, while it obviously was not.
I think that the transaction didn't throw an exception or something like this, so the message maybe indicates that "technically"everything worked fine but in this case the experience is disturbing for the end user who understand that everything is OK with his mint ^^.
In the other case, maybe something does not receive or interpret well the response of the SC in the dapp ?

**Comment by Buky33** [comment]
Excuse me in advance if I disturb you with my questions, do not hesitate to tell me if i do. I'm trying to improve the user experience to see if I could dream of a possible project with the help of all your nice work ;)

**Comment by juliancwirko** [comment]
No worries, please ask :) 

A successful transaction doesn't mean that the smart contract response was also successful. It will probably need some improvements there in the Dapp. But if the token wasn't minted, the counter of minted tokens shouldn't change.

As for the gas limit and the Dapp, it is configured here: https://github.com/ElvenTools/elven-tools-dapp/blob/main/config/nftSmartContract.ts. To be honest, I don't remember why there is 14000000, and in CLI it's lower ;) I probably forgot to change that after changing it in the CLI.

The CLI and Dapp can't know what the limit should be based on a smart contract. Of course, you could implement some transaction simulations, and based on that, you could try to calculate the proper gas limit before making the transaction, but for now, IMO, this is an overhead, maybe later. The gas limit can be predefined as it is now, but it should always be adjusted to the modified smart contract.

**Comment by juliancwirko** [comment]
btw: you can check all three projects and their kanban boards to see what are the plans for them
https://github.com/orgs/ElvenTools/projects?type=classic

**Comment by Buky33** [comment]
Ahah thank you, so you are telling me I had luck when the dapp still could mint my collection ;)

I will take a look at the cli mint method soon, I noticed that it is able to display the response of the transaction, i.e. the failure on my tests, and check if the dapp can have the same response, it might be useful. Perhaps you have already tried and it is impossible?

Thank you for the boards of your projects, I have already read a few and many TODO work items are of particular interest to me.

I have a question, I'm trying to do something very special and I would like to have your opinion on the feasibility of this idea.
I would remove a specific NFT from mint sessions, or add it after, or whatever, so I can gift it to someone specific at the end of the mint.
What do you think about it?

**Comment by juliancwirko** [comment]
Yes, you're right. The Dapp could use the same status as cli: https://github.com/ElvenTools/elven-tools-cli/blob/main/src/utils.ts#L455. The Dapp already uses TransactionWatcher. I have a TODO item to improve the UX of the signing flow. I will add the info about it there.

As for the 'special treatment' for the tokens in the collection, Elven Tools doesn't do that and will probably never do (well, at least not the current smart contract). This is because of the main idea to give equal chances to everyone, even the owner of the contract or their friends, etc. Even giveaway is random. But I think this is what 'tiers' will be in the official Elrond collection next minter. You can also check it here: https://github.com/ElrondNetwork/sc-nft-collection-minter.

As for the gas limits and config in Dapp, yes, you were lucky ;) I will change the configuration to be more dynamic, and Dapp will query the smart contract for most of the configuration (not the gas limit). Additionally, it will be possible to add them as env vars to save some API bandwidth.

**Comment by Buky33** [comment]
I agree with you and share your opinion that everyone should have an equal chance regarding NFTs and collections, that is the benefit and indeed the purpose of the Mint. However, I would provide a variety of challenges and if chance brings a worthless reward, the lucky winner will be quite baffled :)

**Comment by Buky33** [comment]
Anyway that could be fun for the minters 😄

**Comment by juliancwirko** [comment]
I am unsure if this could be related, but I found a slight difference in the gas limit required when the drop is enabled. It wasn't a problem some time ago. Maybe something changed in the network when it comes to gas calculations. 

Min base gas limit for minting was increased to 13000000 from 12500000 in v1.14.0

**Comment by Buky33** [comment]
Hey, interesting feedback.
I hadn't noticed that increase in the gas limit, I'll try it with that value. Actually, it should work fine since the amount needed was 1277....
For your information, I am working with allow lists at the moment, creating some special lists with specials rights, based on your project. Its still very pleasant to use your base code, congratulations again for your great code! I added many endpoints to manage SFT, burn features, and others things.
it's very exciting to learn a lot of things :)
++
