### ISSUE TITLE
NFTs format type

### ISSUE THREAD

**Issue by vitorribeiro99** [ElvenTools/elven-tools-cli#38]
Is it possible to create NFTs with PDF format?

**Comment by juliancwirko** [comment]
Elven Tools don't support all types yet. I'll add it to the TODO kanban board. But I think the pdf isn't endorsed by Elrond API services anyway: https://docs.elrond.com/developers/nft-tokens/#supported-media-types.

Of course, technically, you could upload a pdf to IPFS and link it on-chain, but Elrond APIs won't recognize the file format (Explorers, Maiar App, etc.). So I think I will implement all the types from the official list linked above. Unfortunately, the pdf format isn't included there.
