### ISSUE TITLE
.sign() Promise not awaited

### ISSUE THREAD

**Issue by Buky33** [ElvenTools/elven-tools-cli#40]
Hello how is it going?
I noticed you don't await a promise in the cli / utils.ts file.
When you sign transactions before sending them, you use:
` signer.sign(tx);`

This method is defined as a Promise, so why not await it?
Would it even be a mistake to await it for some reason?

++

I've read all your commits since the last time we exchanged, and all the work you've done with the hooks, it's getting very neat. Congrats!

**Comment by juliancwirko** [comment]
Hi, I'm sorry I somehow missed the issue. 

I am not sure why it is typed as a Promise. I don't see any reason for that in the code here: https://github.com/multiversx/mx-sdk-js-wallet/blob/main/src/userSigner.ts#L31, But I may be missing something. Anyway, it works well as it is.

**Comment by Buky33** [comment]
Hey, that's right.
Rather strange this method signature, I don't see why it is defined as a promise either.
Thanks for looking ;)
++
